In [13]:
label_to_points = new_df.set_index('label').to_dict()['points']

point_to_label = {}
for k, v in label_to_points.items():
    for aaa in v:
        aaa = [round(i, 2) for i in aaa]
        new_key = '_'.join(list(map(str, aaa)))
        point_to_label[new_key] = k

In [16]:
point_to_search = '-4.52_-6.91_3.89'
cluster_of_the_said_point = point_to_label[point_to_search]
other_points_of_same_cluster = label_to_points[cluster_of_the_said_point]

In [12]:
my_points = np.asarray(final_pointcloud.points).tolist()

import pandas as pd
df = pd.DataFrame(list(zip(my_points, labels.tolist())), columns=['points', 'label'])

new_df = df.groupby('label').agg(list).reset_index()[['label', 'points']]

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import open3d as o3d

In [7]:
pcd = o3d.io.read_point_cloud('fused.ply')
# o3d.visualization.draw_geometries([pcd])
print(pcd)
print(np.asarray(pcd.points))

PointCloud with 5347680 points.
[[-4.52022076 -6.90660381  3.89185667]
 [-4.51259804 -6.90450573  3.88614941]
 [-3.10250163 -6.91176987  3.94606209]
 ...
 [ 4.98769617 -3.68095613  4.88237619]
 [-0.10061067 -4.45317745  4.75001812]
 [-0.40276062 -4.42553425  4.62305737]]


In [ ]:
pcd = o3d.io.read_point_cloud('fused.ply')
# o3d.visualization.draw_geometries([pcd])
print(pcd)
print(np.asarray(pcd.points))

In [8]:
Zmin = 3.89
Zmax = 4.2
d = 0.1
final_pointcloud_array = []
pointcloud_as_array = np.asarray(pcd.points)

for point in pointcloud_as_array:
    if  Zmin - d < point[2] < Zmax + d:
        final_pointcloud_array.append(point)
final_pointcloud = o3d.geometry.PointCloud()
final_pointcloud.points = o3d.utility.Vector3dVector(final_pointcloud_array)
# o3d.visualization.draw_geometries([final_pointcloud])

In [11]:
with o3d.utility.VerbosityContextManager(
    o3d.utility.VerbosityLevel.Debug) as cm:
    labels = np.array(
        final_pointcloud.cluster_dbscan(eps=0.05, min_points=4, print_progress=True))

[Open3D DEBUG] Precompute neighbors.
Precompute neighbors.[================>                       ] 37%                                    ] 5%
[Open3D DEBUG] Compute Clusters
Precompute neighbors.[========================================] 100%293=======================>        ] 77%
Clustering[======>                                 ] 15%


In [10]:
max_label = labels.max()
print(f"point cloud has {max_label + 1} clusters")
colors = plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1))
colors[labels < 0] = 0
final_pointcloud.colors = o3d.utility.Vector3dVector(colors[:, :3])
# o3d.visualization.draw_geometries([final_pointcloud], mesh_show_wireframe=True, point_show_normal=True)
print(labels.shape)

NameError: name 'labels' is not defined

In [18]:
viewer = o3d.visualization.Visualizer()
viewer.create_window()
for geometry in geometries:
viewer.add_geometry(geometry)
opt = viewer.get_render_option()
opt.show_coordinate_frame = True
opt.background_color = np.asarray([0.5, 0.5, 0.5])
viewer.run()
viewer.destroy_window()

IndentationError: expected an indented block (3733856709.py, line 4)

In [17]:
point_to_search = '1.31_3.98_4.28'
cluster_of_the_said_point = point_to_label[point_to_search]
other_points_of_same_cluster = label_to_points[cluster_of_the_said_point]
print(cluster_of_the_said_point)

50
